# Generated by Django 3.2.7 on 2021-09-22 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100)),
                ('cpf', models.CharField(default='', help_text='CPF', max_length=14)),
                ('email', models.CharField(default='', help_text='e-mail', max_length=100)),
                ('celular', models.CharField(default='', help_text='celular', max_length=100)),
                ('rg', models.CharField(default='', help_text='rg', max_length=100)),
                ('endereco', models.CharField(default='', help_text='endereco', max_length=100)),
                ('salario', models.CharField(default='', help_text='salario', max_length=100)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
